### ISSUE TITLE
without email config, strange error

### ISSUE THREAD

**Issue by GeoffreyPlitt** [zemirco/lockit#33]
Hi,

Instead of using a config.js file, I'm just constructing the config in my app.js for a quite prototype. I know I don't have an email config, but this error is strange, why does it point to index.js:38?

```javascript
lockit no email config found. Check your database for tokens.
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: missing path
    at Module.require (module.js:363:3)
    at require (module.js:384:17)
    at new module.exports (/vagrant/node_modules/lockit/index.js:38:44)
    at Object.<anonymous> (/vagrant/app.js:20:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
````

**Comment by GeoffreyPlitt** [comment]
Oh I'm using a MSSQL database. I didn't see that listed in your supported DBs, but Sequelize can handle it, so I figured that would be OK.
