### ISSUE TITLE
Cannot find module:  lockit-template-blank

### ISSUE THREAD

**Issue by dennishall1** [zemirco/lockit#50]
It's really really easy to get this error, including if you just make a new express app using defaults and try the quick-start with lockit as per the instructions in lockit's readme:

`npm start`

`lockit no db config found. Using SQLite.`
`lockit no email config found. Check your database for tokens.`

/signup

..fill in the form and submit it..

->

```
Unhandled rejection Error: Cannot find module 'lockit-template-blank'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new module.exports (/Users/dhall/projects/myapp/node_modules/lockit/node_modules/lockit-signup/node_modules/lockit-sendmail/index.js:16:19)
```

**Comment by dennishall1** [comment]
I went into  node_modules/lockit/node_modules/lockit-signup .. and changed its package.json .. I just put all the devDependencies into the regular dependencies, ran `npm i`, then re-ran the app, and this error went away.  Probably lockit-template-blank should be a regular dependency for that module, not a devDependency. ..  considering that the instructions in Lockit's readme fail otherwise.
